services:
  maze:
    image: suranyami/maze:latest
    environment:
      PHX_HOST: maze.suranyami.com
      PORT: "4000"
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?SECRET_KEY_BASE is required}
    x-ports:
      - maze.suranyami.com:4000/https