defmodule Maze.SpectreGrid do
  @moduledoc """
  An aperiodic maze grid based on the spectre monotile
  (Smith, Myers, Kaplan, Goodman-Strauss, 2023).

  ## How the tiling is generated

  The spectre tile is a chiral aperiodic monotile: a 14-sided polygon with all
  edges of length 1.  Its tiling is generated by a **substitution system** with
  nine metatile types (Gamma, Delta, Theta, Lambda, Xi, Pi, Sigma, Phi, Psi).
  Each metatile expands into eight child metatiles according to fixed rules; at
  the leaf level every metatile resolves to one spectre polygon (two for Gamma).

  The substitution and coordinate algorithm is ported from the Python reference
  implementation by Shrx (github.com/shrx/spectre), which is itself based on
  the original paper and Kaplan's reference code.

  ## Maze representation

  Each spectre polygon is a cell.  Two cells are adjacent when they share an
  edge (detected by matching rounded vertex coordinates).  The grid supports
  `link/3`, `linked?/3`, `unvisited_neighbours/2`, and `weave_candidates/2`
  (always empty — no weaving), so it works directly with `RecursiveBacktracker`.

  Cell IDs are non-negative integers assigned in tiling-generation order.
  Use `start: 0` when calling `RecursiveBacktracker.on/2`.
  """

  # √3/2 — used for all vertex coordinates
  @s2 1.7320508075688772 / 2

  # 14 spectre vertices in local coordinates (all edges length 1)
  @spectre_points [
    {0.0, 0.0},
    {1.0, 0.0},
    {1.5, -@s2},
    {1.5 + @s2, 0.5 - @s2},
    {1.5 + @s2, 1.5 - @s2},
    {2.5 + @s2, 1.5 - @s2},
    {3.0 + @s2, 1.5},
    {3.0, 2.0},
    {3.0 - @s2, 1.5},
    {2.5 - @s2, 1.5 + @s2},
    {1.5 - @s2, 1.5 + @s2},
    {0.5 - @s2, 1.5 + @s2},
    {-@s2, 1.5},
    {0.0, 1.0}
  ]

  # Indices into @spectre_points used as "quad" attachment points
  @quad_indices [3, 5, 7, 11]

  # Substitution rules: each type expands to 8 child-type slots (nil = skip)
  @super_rules %{
    "Gamma" => ["Pi", "Delta", nil, "Theta", "Sigma", "Xi", "Phi", "Gamma"],
    "Delta" => ["Xi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    "Theta" => ["Psi", "Delta", "Pi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    "Lambda" => ["Psi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    "Xi" => ["Psi", "Delta", "Pi", "Phi", "Sigma", "Psi", "Phi", "Gamma"],
    "Pi" => ["Psi", "Delta", "Xi", "Phi", "Sigma", "Psi", "Phi", "Gamma"],
    "Sigma" => ["Xi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Lambda", "Gamma"],
    "Phi" => ["Psi", "Delta", "Psi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    "Psi" => ["Psi", "Delta", "Psi", "Phi", "Sigma", "Psi", "Phi", "Gamma"]
  }

  # [cumulative_angle_deg, from_quad_index, to_quad_index]
  # Encodes how each of the 7 non-anchor child positions is placed relative
  # to the previous child (child 0 is relative to child 7, the anchor).
  @transformation_rules [
    {60, 3, 1},
    {0, 2, 0},
    {60, 3, 1},
    {60, 3, 1},
    {0, 2, 0},
    {60, 3, 1},
    {-120, 3, 3}
  ]

  @type id :: non_neg_integer()

  @type t :: %__MODULE__{
          cells: %{id() => %{vertices: [{float(), float()}], neighbors: [id() | nil]}},
          links: MapSet.t()
        }

  defstruct [:cells, :links]

  @doc """
  Generate an empty spectre-tiling maze grid at the given expansion depth.

  | depth | approx. tiles | generation time |
  |-------|--------------|-----------------|
  |   2   |    ~50       | < 100 ms        |
  |   3   |    ~350      | < 500 ms        |
  |   4   |    ~2 500    | ~2–5 s          |
  """
  @spec new(pos_integer()) :: t()
  def new(depth \\ 3) do
    polygons = generate_polygons(depth)
    indexed = Enum.with_index(polygons, fn verts, i -> {i, verts} end)
    adjacency = compute_adjacency(indexed)
    cells = build_cells(indexed, adjacency)
    %__MODULE__{cells: cells, links: MapSet.new()}
  end

  @doc "Open a bidirectional passage between `id1` and `id2`."
  @spec link(t(), id(), id()) :: t()
  def link(%__MODULE__{links: links} = grid, id1, id2) do
    %{grid | links: MapSet.put(links, canonical(id1, id2))}
  end

  @doc "Return true when there is an open passage between `id1` and `id2`."
  @spec linked?(t(), id(), id()) :: boolean()
  def linked?(%__MODULE__{links: links}, id1, id2) do
    MapSet.member?(links, canonical(id1, id2))
  end

  @doc "Return all neighbours of `id` that have not yet been linked to any cell."
  @spec unvisited_neighbours(t(), id()) :: [id()]
  def unvisited_neighbours(%__MODULE__{cells: cells, links: links}, id) do
    cells[id].neighbors
    |> Enum.reject(&is_nil/1)
    |> Enum.uniq()
    |> Enum.reject(&visited?(&1, links))
  end

  @doc "Spectre grids do not support weaving — always returns `[]`."
  @spec weave_candidates(t(), id()) :: []
  def weave_candidates(%__MODULE__{}, _id), do: []

  # ---------------------------------------------------------------------------
  # Tiling generation
  # ---------------------------------------------------------------------------

  # Produce a flat list of spectre polygons (each: list of 14 {x,y} vertices).
  defp generate_polygons(depth) do
    base_quad = base_quad_points()

    # Build level-transform lists from deepest to shallowest (prepend = deepest first).
    {levels, _} =
      Enum.reduce(1..depth, {[], base_quad}, fn _i, {levels, quad} ->
        {transforms, super_quad} = build_level_transforms(quad)
        {[transforms | levels], super_quad}
      end)

    expand(levels, "Gamma", identity())
  end

  # Base case: produce actual spectre polygon(s) for a leaf tile.
  defp expand([], "Gamma", world_t) do
    [
      apply_t(world_t, @spectre_points),
      apply_t(mul(world_t, gamma2_transform()), @spectre_points)
    ]
  end

  defp expand([], _type, world_t) do
    [apply_t(world_t, @spectre_points)]
  end

  # Recursive case: expand this metatile using the deepest (front) level's transforms.
  defp expand([level_transforms | rest], type, world_t) do
    @super_rules[type]
    |> Enum.with_index()
    |> Enum.flat_map(fn {child_type, i} ->
      if is_nil(child_type) do
        []
      else
        child_t = Enum.at(level_transforms, i)
        expand(rest, child_type, mul(world_t, child_t))
      end
    end)
  end

  # Compute the 8 child-placement transforms for one expansion level, plus the
  # super-quad (attachment points) needed for the next level.
  #
  # Algorithm ported from buildSupertiles() in the Python reference (shrx/spectre).
  defp build_level_transforms(quad) do
    # Walk through the 7 transformation rules, accumulating transforms.
    # transformations[0] = identity (anchor for child slot 0).
    # Each rule appends one more transform for child slots 1–7.
    init = {[identity()], 0, identity(), quad}

    {transforms, _, _, _} =
      Enum.reduce(@transformation_rules, init, fn {angle, from_q, to_q},
                                                  {ts, total_angle, rotation, t_quad} ->
        {new_angle, new_rot, new_tq} =
          if angle != 0 do
            ta = total_angle + angle
            r = trot(:math.pi() * ta / 180.0)
            tq = Enum.map(quad, &trans_pt(r, &1))
            {ta, r, tq}
          else
            {total_angle, rotation, t_quad}
          end

        # Translate so that the new tile's rotated quad[to_q] lands on the world
        # position of the previous tile's quad[from_q].
        prev_t = List.last(ts)
        world_target = trans_pt(prev_t, Enum.at(quad, from_q))
        rotated_src = Enum.at(new_tq, to_q)

        ttt =
          ttrans(
            elem(world_target, 0) - elem(rotated_src, 0),
            elem(world_target, 1) - elem(rotated_src, 1)
          )

        {ts ++ [mul(ttt, new_rot)], new_angle, new_rot, new_tq}
      end)

    # Apply reflection matrix R = {-1, 0, 0, 0, 1, 0} to all transforms.
    reflected = Enum.map(transforms, &mul(reflection(), &1))

    # Compute the 4 attachment points for the next expansion level.
    super_quad = [
      trans_pt(Enum.at(reflected, 6), Enum.at(quad, 2)),
      trans_pt(Enum.at(reflected, 5), Enum.at(quad, 1)),
      trans_pt(Enum.at(reflected, 3), Enum.at(quad, 2)),
      trans_pt(Enum.at(reflected, 0), Enum.at(quad, 1))
    ]

    {reflected, super_quad}
  end

  # ---------------------------------------------------------------------------
  # Adjacency detection (shared edges)
  # ---------------------------------------------------------------------------

  defp compute_adjacency(indexed_polygons) do
    n = length(@spectre_points)

    edge_map =
      Enum.flat_map(indexed_polygons, fn {id, vertices} ->
        vertices
        |> Stream.with_index()
        |> Enum.map(fn {v1, i} ->
          v2 = Enum.at(vertices, rem(i + 1, n))
          {edge_key(v1, v2), {id, i}}
        end)
      end)
      |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))

    # Edges shared by exactly 2 tiles are interior passages.
    edge_map
    |> Enum.filter(fn {_, tiles} -> length(tiles) == 2 end)
    |> Enum.map(fn {_, [{id1, e1}, {id2, e2}]} -> {id1, e1, id2, e2} end)
  end

  defp build_cells(indexed_polygons, adjacency) do
    n = length(@spectre_points)

    cells =
      Map.new(indexed_polygons, fn {id, vertices} ->
        {id, %{vertices: vertices, neighbors: List.duplicate(nil, n)}}
      end)

    Enum.reduce(adjacency, cells, fn {id1, e1, id2, e2}, acc ->
      acc
      |> update_in([id1, :neighbors], &List.replace_at(&1, e1, id2))
      |> update_in([id2, :neighbors], &List.replace_at(&1, e2, id1))
    end)
  end

  # Round to 6 decimal places to absorb floating-point drift, then sort endpoints
  # so the key is direction-independent.
  defp edge_key({x1, y1}, {x2, y2}) do
    p1 = {round(x1 * 1_000_000), round(y1 * 1_000_000)}
    p2 = {round(x2 * 1_000_000), round(y2 * 1_000_000)}
    if p1 <= p2, do: {p1, p2}, else: {p2, p1}
  end

  # ---------------------------------------------------------------------------
  # Affine transform helpers
  # Transform tuple: {a, b, tx, c, d, ty}  →  | a  b  tx |
  #                                             | c  d  ty |
  #                                             | 0  0  1  |
  # ---------------------------------------------------------------------------

  defp identity, do: {1.0, 0.0, 0.0, 0.0, 1.0, 0.0}
  defp reflection, do: {-1.0, 0.0, 0.0, 0.0, 1.0, 0.0}

  defp trot(rad) do
    c = :math.cos(rad)
    s = :math.sin(rad)
    {c, -s, 0.0, s, c, 0.0}
  end

  defp ttrans(dx, dy), do: {1.0, 0.0, dx, 0.0, 1.0, dy}

  # Compose transforms: mul(T1, T2)(p) = T1(T2(p))
  defp mul({a1, b1, tx1, c1, d1, ty1}, {a2, b2, tx2, c2, d2, ty2}) do
    {
      a1 * a2 + b1 * c2,
      a1 * b2 + b1 * d2,
      a1 * tx2 + b1 * ty2 + tx1,
      c1 * a2 + d1 * c2,
      c1 * b2 + d1 * d2,
      c1 * tx2 + d1 * ty2 + ty1
    }
  end

  defp trans_pt({a, b, tx, c, d, ty}, {x, y}), do: {a * x + b * y + tx, c * x + d * y + ty}

  defp apply_t(transform, vertices), do: Enum.map(vertices, &trans_pt(transform, &1))

  defp base_quad_points do
    Enum.map(@quad_indices, &Enum.at(@spectre_points, &1))
  end

  # The second spectre in a Gamma base tile: rotate 30° then translate to vertex 8.
  defp gamma2_transform do
    {p8x, p8y} = Enum.at(@spectre_points, 8)
    mul(ttrans(p8x, p8y), trot(:math.pi() / 6.0))
  end

  defp canonical(a, b) when a <= b, do: {a, b}
  defp canonical(a, b), do: {b, a}

  defp visited?(id, links) do
    Enum.any?(links, fn {a, b} -> a == id or b == id end)
  end
end
